---
abstract: 'ease non-blocking I/O streams based on EV'
author:
  - 'Alex Efros <powerman-asdf@ya.ru>'
build_requires:
  Test::Exception: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Stream
no_index:
  directory:
    - inc
    - t
recommends:
  Data::Alias: 0.08
requires:
  EV: 0
  EV::ADNS: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.000003
